name: 'ember-cli-update-action'
description: 'Run blueprint updates on CI'
inputs:
  git_email:
    description: 'git email'
  git_name:
    description: 'git name'
  amend:
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
