name: 'ember-cli-update-action'
description: 'Run blueprint updates on CI'
inputs:
  git_email:
    description: 'git email'
  git_name:
    description: 'git name'
  amend:
    default: false
  install_command:
    description: 'supply your own package install command'
  autofix_command:
    description: 'post-update linting autofix code'
runs:
  using: 'node12'
  main: 'dist/index.js'
