name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint-git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: |
        git fetch --prune --unshallow
        git branch master origin/master

    - uses: actions/setup-node@v1.1.0

    - run: npm ci
    - run: npm run lint:git

  lint-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0

    - run: npm ci
    - run: npm run lint:js
