name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint-git:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - run: |
        git fetch --prune --unshallow
        git branch master origin/master

    - uses: actions/setup-node@v2
      with:
        node-version: 12

    - run: npm ci
    - run: npm run lint:git

  lint:
    needs: lint-git

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12

    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        node:
        - 12

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci
    - run: npm test

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v3
      with:
        node-version: 12

    - uses: kellyselden/ember-cli-update-action@v3
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
