name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint-git:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run: |
        git fetch --prune --unshallow
        git branch master origin/master

    - uses: actions/setup-node@v1.1.0

    - run: npm ci
    - run: npm run lint:git

  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        node:
        - 8

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node }}

    - run: npm ci
    - run: npm run lint:js

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v1.1.0
    - uses: kellyselden/ember-cli-update-action@master
      with:
        autofix_command: npm run lint:js -- --fix
