name: CI

on:
  # allow manual running
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  lint-git:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - run: |
        git fetch --prune --unshallow
        git branch main origin/main

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci
    - run: npm run lint:git

  lint:
    needs: lint-git

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        node:
        - 18

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci
    - run: npm test

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - uses: kellyselden/ember-cli-update-action@v6
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
        commit_prefix: "chore: "
